### PR TITLE
List profiles

### PR DESCRIPTION
**Pull request by cledvina**
The profile editor now creates, reads, updates and deletes profiles from verso. 

I disabled overwriting a profile record based on a matching title.   A warning is thrown that alerts the user that the title is not unique.

Vocabularies do not load now, since all of the server functions point to verso-- but I will get that working tomorrow.

### CODE REVIEW

**Comment by cledvina** [comment]
The vocabularies have been loaded into verso.  Profile-edit now reads vocabs from verso and populates the select box.  There still is some work to do to get the objects to display properly in vocab list-- That'll have to wait until Monday.

**Comment by cledvina** [comment]
Ok, Kirk:

The RDF data model is slightly different as stored in verso.  The actually text values are stored in the __text element.  This is why we were getting the [Object Object] error in the resources/property lists.

Everything looks good now.

**Comment by cledvina** [comment]
The profile editor now fetches languages from verso.  The profile-editor still gets templateRefs from the file server.  Should these be moved over to verso as well?

**Comment by wafschneider** [comment]
I think moving templateRefs to verso is part of requirement 3.1.2, so maybe hold off on that for now?

**Pull request merged**
